### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by jimmy1357** [LambdaWx/CNN_sentence_tensorflow#3]
您好，
我在使用您提供的代码，在v1.1.0的tf上训练文本分类模型，遇到如下错误：
Traceback (most recent call last):
  File "sentence_classfier_with_tensorflow.py", line 236, in <module>
    _, step, summaries = sess.run([train_step, global_step, train_summary_op],feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed>
请问一下这是什么情况呢？

**Comment by gpcv-liujin** [comment]
您好，我也遇到了类似的问题，请问您解决了吗？
